test:
    controller:
	state:
	    type: joint_state_controller/JointStateController
	    publish_rate: 50
	position:
	    robot_joint_1:
		type: effort_controllers/JointPositionController
		joint: robot_joint_1
		pid: {p: 10.0, i: 0.0, d: 1.0}
	    robot_joint_2:
		type: effort_controllers/JointPositionController
		joint: robot_joint_1
		pid: {p: 5.0, i: 2.0, d: 1.0} 
